micronaut:
  application:
    name: hello-world
  aot:
    enabled: true
    optimizations:
      service-loading: true
logging:
  level:
    root: INFO
  appenders:
    - type: CLOUDWATCH
      name: cloudwatch
